id: I99EA194B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:21:04+00:00'
last_modified: '2022-06-08T12:07:47.902508+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25995
  title: ཆོས་འབྱུང་མཁས་པའི་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    CCAB:
      image_group_id: I1GS55140
      title: ''
      total_pages: 297
      order: 1
      base_file: CCAB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
