id: P009593
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:46.392593
source_metadata:
  id: bdr:W25995
  title: ཆོས་འབྱུང་མཁས་པའི་དགོངས་རྒྱན།
  author: ''
  volumes:
    d62ac44f6f954cfe9c14b0c65c76810e:
      image_group_id: I1GS55140
      title: ''
      volume_number: 1
      total_pages: 297
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
