id: P009593
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W25995
  title: ཆོས་འབྱུང་མཁས་པའི་དགོངས་རྒྱན།
  author: ''
  volumes:
    d62ac44f6f954cfe9c14b0c65c76810e:
      image_group_id: I1GS55140
      title: ''
      volume_number: 1
      total_pages: 297
      base_file: v001.txt
